### ISSUE TITLE
Unused code about anchor boxes

### ISSUE THREAD

**Issue by drgnjoon** [hova88/PointPillars_MultiHead_40FPS#6]
Hi, first of all, thank you for sharing your code.

I wonder that in pointpillars.cc, line 167~ shows initiate anchor sizes from yaml file. But i cannot find using that vectors in this repository.

Could you explain about this part?

Thank you.

**Comment by hova88** [comment]
> Hi, first of all, thank you for sharing your code.
> 
> I wonder that in pointpillars.cc, line 167~ shows initiate anchor sizes from yaml file. But i cannot find using that vectors in this repository.
> 
> Could you explain about this part?
> 
> Thank you.

because all the content related to **anchor** is (and should be) encoded in `multihead.onnx` file, the variables you mentioned do not need to be used. for more details, you can see [AnchorHeadMulti/hova88/OpenPCdet](https://github.com/hova88/OpenPCDet/blob/master/tools/onnx_utils/onnx_dense_head.py#L205). However, since TensorRT 6.0 does not support such operation, I still put some related stuff here.
